package Charcoal::Model::PgDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Charcoal::Schema::PgDB',
    
    
);

=head1 NAME

Charcoal::Model::PgDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Charcoal>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Charcoal::Schema::PgDB>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

Nishant Sharma

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
